export const postFooter=[
    {
        name:"Like",
        imageUrl:"https://img.icons8.com/fluency-systems-regular/60/ffffff/like--v1.png",
        clickedImageUrl:"https://img.icons8.com/fluency-systems-regular/60/f44336/like--v1.png"
    },
    {
        name:"Message",
        imageUrl:"https://img.icons8.com/material-outlined/60/ffffff/speech-bubble--v1.png"
    },
    {
        name:"Share",
        imageUrl:"https://img.icons8.com/external-creatype-outline-colourcreatype/64/ffffff/external-paper-user-interface-creatype-outline-colourcreatype.png"
    },
    {
        name:"Save",
        imageUrl:"https://img.icons8.com/material-outlined/60/ffffff/bookmark-ribbon--v1.png",
        clickedImageUrl:"https://img.icons8.com/ios-glyphs/30/ffffff/bookmark-ribbon.png"
    }
]